### ISSUE TITLE
More information is needed for queries execution

### ISSUE THREAD

**Issue by SlavaUtesinov** [jsreport/jsreport-sql-store#2]
I am developing module like `jsreport-oracle-store`. There is a problem with `Edm.Boolean` type columns - such columns are represented by `number(1)` type [oracle.js](https://github.com/pofider/node-odata-to-sql/blob/master/lib/types/oracle.js). As a result, after I had retrieved rows I had to convert `1/0` values to `true/false` respectively. But not all columns with number type denote `Edm.Boolean` - some of them are really numbers, so I need some additional information during queries execution not only `q, this.opts`, may be also `this.entitySet` to make desicion about actual type of columns and need to do mentioned conversions.

```
async toArray () {
  const q = this.odataSql.query(this.entitySet, this.query)
  const res = await this.executeQuery(q, this.options)
  return res.records.map((r) => this.odataSql.parse(this.entitySet, r))
}
```

**Comment by pofider** [comment]
Yes, good point. I added the entity set.
https://github.com/jsreport/jsreport-sql-store
