### ISSUE TITLE
Update odata-to-sql

### ISSUE THREAD

**Issue by jorisdebock** [jsreport/jsreport-sql-store#3]
@pofider can you update this package so I can use this in the oracle store?
https://github.com/jsreport/jsreport/issues/779

**Comment by pofider** [comment]
done

**Comment by jorisdebock** [comment]
@pofider thx, can you also push a new version of this library?

**Comment by pofider** [comment]
Yes sure, are you close to finishing?
I mean you can use the git dependency until then because other problems could pop-up which could require another release of this package.
